### ISSUE TITLE
Support for yargs 3.28.0

### ISSUE THREAD

**Issue by nexdrew** [nexdrew/yargonaut#7]
This version of yargs added better handling of ANSI escape codes, but it appears that this can adversely affect the application of colors _and_ fonts within yargonaut - namely it removes preceding whitespace from rendered fonts (i.e. lines that begin with whitespace have their whitespace trimmed).

Here's an example. Note the first line of "Commands:", "Options:", and "Examples:" is off.
<img width="719" alt="screen shot 2015-10-17 at 12 30 50 am" src="https://cloud.githubusercontent.com/assets/1929625/10557004/841e22ba-7466-11e5-812a-5eaf6ab6e43d.png">

See if there's something yargonaut can do to avoid this.

**Comment by bcoe** [comment]
@nexdrew I bet we can get the cliui ansi escape tests running without trimming the end of lines.

**Comment by nexdrew** [comment]
@bcoe I will do my best to take a look at the cliui tests tomorrow. Thanks!

**Comment by nexdrew** [comment]
@bcoe I started looking into cliui today. Something going on with left padding when ANSI escape codes are used. I'll get to the bottom of it tomorrow.

**Comment by nexdrew** [comment]
See [cliui PR 13](https://github.com/bcoe/cliui/pull/13).

**Comment by bcoe** [comment]
@nexdrew I've published a release candidate of yargs with your changes to cliui:

`npm install yargs@next`

Let me know if this does the trick and I'll get the version promoted to latest. I've also pulled in some parsing fixes I made, and a few other tweaks, the extra set of eyes is much appreciated.

**Comment by nexdrew** [comment]
@bcoe Yes, now that `cliui@3.0.3` is being used by yargs, everything looks great! :+1: Thanks, Ben.

(Note that ANSI output works with `yargs@3.28.0` and `yargs@3.29.0` now, since their cliui semver dependency both resolve to `cliui@3.0.3`)

Here's the example again, now fixed:
<img width="712" alt="screen shot 2015-10-21 at 9 28 22 am" src="https://cloud.githubusercontent.com/assets/1929625/10637919/39b4cd32-77d6-11e5-9f52-b9658a4a1565.png">
