### ISSUE TITLE
Style choices values

### ISSUE THREAD

**Issue by dogoku** [nexdrew/yargonaut#9]
Is it possible to style the choices values, instead of just the "choices:" string

For example, can I style the words "chrome","firefox,"IE", etc?
```
Options:
  --browser, -b    The name of a browser. Only usable for tests.
  [string] [choices: "chrome", "firefox", "IE", "Chrome_debug", "Firefox_debug"]
```

I've tried some of the keys given by `.getAllKeys()` but none of them seem to correspond to choice values

Thanks

**Comment by gil0mendes** [comment]
That would be nice, as well give some color to the commands set.

**Comment by nexdrew** [comment]
@dogoku @gil0mendes Hi there, sorry I never responded to this! I'm actually not maintaining yargonaut any more, but the yargs architecture doesn't allow us to style `choices` values anyway.

The way yargonaut works is by overriding the [i18n strings defined in yargs](https://github.com/yargs/yargs/blob/a70b285c0f163a000f38be3e70d5f6c21af635f0/locales/en.json), and so it's limited to only supporting those strings. Anything defined/rendered outside of those strings/templates can't be overridden.

Since I got frustrated with certain limitations in the yargs architecture (like this and the lack of support for asynchronous commands), I wrote another CLI library that lets you customize things (particularly the generated help content) much more fully. It's called **sywac**, check it out:

https://github.com/sywac/sywac
http://sywac.io

With sywac you can style `choices` values (and much more) using [style hooks](http://sywac.io/docs/sync-config.html#style). Here's an example:

```js
#!/usr/bin/env node

const chalk = require('chalk')

require('sywac')
  .enumeration('-c, --color <color>', {
    desc: 'Pick a color',
    choices: ['blue', 'yellow', 'green']
  })
  .help('-h, --help')
  .style({
    hints: colorize,
    messages: colorize
  })
  .outputSettings({ maxWidth: 65 })
  .parseAndExit()
  .then(argv => {
    console.log(argv)
  })

function colorize (str) {
  return str
    .replace('blue', chalk.blue('blue'))
    .replace('yellow', chalk.yellow('yellow'))
    .replace('green', chalk.green('green'))
}
```

![screen shot 2017-12-14 at 2 11 03 pm](https://user-images.githubusercontent.com/1929625/34009901-b0d56db4-e0d8-11e7-886d-91666fa20ebb.png)

I realize switching from one library to another is not always easy or ideal, but it's the best I can offer at the moment. Thanks for your interest in yargonaut!

**Comment by gil0mendes** [comment]
@nexdrew The `sywac` looks interesting, I'll take a look at it in the next weeks time. Yep, I agree with you `yargs` has some architectural limitations and, sometimes, even minor releases break my code :(

I use them on a framework that I'm currently working in ([Stellar](https://github.com/stellarFw/stellar/)), but now that I'll make a major refactor I'll use the momentum to replace `yargs` to something better and more stable.

To finalize, `sywac` has some way to declare inner commands? Like the following:

```
// this command will show a help screen with all available sub-commands
stellar make

// this is actually a command to create a new model, that can contain arguments
stellar make model <moda-name> [--module] [--crud] [--help]
```

**Comment by nexdrew** [comment]
@gil0mendes Yes, sywac supports any level of nested commands, and it also makes it easier to [show help by default](http://sywac.io/docs/sync-config.html#showHelpByDefault) and require positional arguments ([with](http://sywac.io/docs/sync-config.html#command) or [without](http://sywac.io/docs/sync-config.html#positional) a command).

Here's an example:

```js
#!/usr/bin/env node
'use strict'

let c
function chalk () {
  if (!c) c = require('chalk') // lazily load chalk, only used if help text displayed
  return c
}

require('sywac')
  .command('make', {
    desc: 'Generate some project components',
    setup: sywac => {
      sywac
        .command('model <model_name>', {
          desc: 'Create a new Model',
          paramsDesc: 'The name of the model to make',
          setup: sywac => {
            sywac
              .string('--module <module>', {
                desc: 'Module where the files will be created',
                defaultValue: 'private'
              })
              .boolean('--force', {
                desc: 'Overwrite existent files'
              })
              .boolean('--crud', {
                desc: 'Create a set of actions with the CRUD operations'
              })
              .string('--actionName <name>', {
                desc: 'Overwrite the action file name'
              })
              .boolean('--rest', {
                desc: 'Generate RESTfull URLs for the generated actions'
              })
          },
          run: argv => {
            console.log(`making model ${argv.model_name}:`, argv)
          }
        })
    }
  })
  .showHelpByDefault() // display help unless a command with "run" method is called
  .boolean('--daemon', {
    desc: 'Execute the command as a daemon'
  })
  .help('-h, --help')
  .version('-v, --version')
  .outputSettings({ maxWidth: 90 })
  .style({
    usagePrefix: str => chalk().yellow(str.slice(0, 6)) + ' ' + chalk().bold(str.slice(7)),
    usageCommandPlaceholder: str => chalk().bold(str),
    usagePositionals: str => chalk().bold(str),
    usageArgsPlaceholder: str => chalk().bold(str),
    usageOptionsPlaceholder: str => chalk().bold(str),
    group: str => chalk().yellow(str),
    flags: str => chalk().bold(str),
    desc: str => chalk().cyan(str),
    hints: str => chalk().gray.dim(str),
    groupError: str => chalk().red.bold(str),
    flagsError: str => chalk().red.bold(str),
    descError: str => chalk().red.bold(str),
    hintsError: str => chalk().red(str),
    messages: str => chalk().red.bold(str) // these are error messages
  })
  .parseAndExit()
```
![screen shot 2017-12-24 at 5 24 51 pm](https://user-images.githubusercontent.com/1929625/34329467-825bbf7a-e8cf-11e7-94e6-de2346624283.png)
![screen shot 2017-12-24 at 5 25 06 pm](https://user-images.githubusercontent.com/1929625/34329468-8d7fef70-e8cf-11e7-8848-50289c07272e.png)
![screen shot 2017-12-24 at 5 25 19 pm](https://user-images.githubusercontent.com/1929625/34329469-94ac1a44-e8cf-11e7-8051-0a2cae2adac4.png)

A couple things to note:

- I didn't show it here, but you can still organize commands in to their own modules, similar to yargs, but use:
    - `flags` instead of `command`
    - `desc` instead of `describe`
    - `setup` (function that accepts `sywac`) instead of `builder`
    - `run` (function that accepts `argv`) instead of `handler`
- Command `run` functions/methods can be `async`, and sywac will wait until they resolve before returning control to higher-level logic
- You can fully customize the help content using [style hooks](http://sywac.io/docs/sync-config.html#style)
- You can override `hints` per-option if you want (use an empty string to disable them)
- The usage content is auto-generated, but you can customize it if you'd like
- Sywac does not currently support shell completion
- Sywac does not currently support recommending commands
- Compare sywac features to yargs features here: http://sywac.io/about/comparison-matrix.html

If you have any more questions, I'd be glad to answer them. I could also potentially help with the refactor of the `stellar` CLI, if you think you'd like to give sywac a try. Just let me know. :+1:

**Comment by gil0mendes** [comment]
Wow... @nexdrew awesome response and thanks for the complete explanation. We'll replace yargs by Sywac for sure, I already created a new [issue](https://github.com/StellarFw/stellar/issues/126) 😉

Any contribution is very welcome, thanks for the offer 😉 If I find something to contribute to Sywac I'll do it as well 🙂

**Comment by binarymist** [comment]
The `usagePrefix` isn't working though.

**Comment by davidkjackson54** [comment]
Is sywac still active or has it been abandoned? I haven't seen any updates for some 6 months and don't want to spend time investigating migrating if it is no longer being maintained.

**Comment by nexdrew** [comment]
Sywac is still active. [See my comment here.](https://github.com/yargs/yargs/issues/251#issuecomment-450189087)

**Comment by Worie** [comment]
I'd only suggest making a note in the readme that Yargs/Yargonaut are no longer maintained in favor of Sywac

**Comment by nexdrew** [comment]
To be clear:

- yargs is still actively maintained by the yargs team
- yargonaut was my own project, and I am no longer maintaining it, but that doesn't mean someone else couldn't take the reins

@jjoselv Do you have any interest in maintaining yargonaut? If so, then let's figure out a way to transfer ownership to you. If not, I can archive this repository or at least add something to the README to clarify the state of things.

@Worie Thanks for the suggestion!
